title: Information Disorder (InDor) Workshop
description: Workshop on Information Disorder co-located with LREC 2026 in Palma de Mallorca, Spain
theme: jekyll-theme-cayman

url: "https://information-disorder-workshop.github.io"
